### ISSUE TITLE
HW5

### ISSUE THREAD

**Issue by rahlk** [LambdaConglomerate/x9115lam#15]
Hey guys,
I see you're eb is greater than 1. It should be normalized so that it lie between 0 and 1.

**Comment by ghost** [comment]
I attempted a dirty fix for energy normalization, but I occasionally get values slightly above 1 (like 1.011...). Assuming this isn't a result of floating point inaccuracy, are we sure that emax is sqrt(2)?

**Comment by meneal** [comment]
So I did a few different things to this:
- I pulled baseline out into it's own separate file and ran it for 10K iterations 4 times.
- I took the max and min values for f1 and f2 and hardcoded them into MaxWalkSat.py.
- I switched the emax value to 1 and just divided the output from the energy function by sqrt(2).
- I made the model run for 1000 retries rather than the 100 we had it set to before.
- I pulled the screenshot from the main page and just link to the output since it's really long now.

So why did I do this stuff:  We were getting values that were still slightly above 1 as Joseph was saying, so the only way I could pull that in line was to run the baseline study for longer to get more accurate numbers for normalizing f1 and f2.  

Since it had to run for so long it seemed better to pull the baseline out and run it separately so that we didn't have to run it every time we run MaxWalkSat.  Also I was thinking that it would be better to separate it out now and then be able to use generalize it in parallel with how we generalize the model testbed.  

That leads to the next part: Why run it so much longer?  Well we aren't getting as close to the theoretical optimum now.  In running this a few times we really don't get much above .85 with 1.0 being the new maximum.  

I think that what's happening at this point is that we are taking the max and min values for f1 and f2 over 40K runs and those values may just be so rare/unlikely that we are just not getting those values in actual runs.  

Anyone have any further thoughts?

**Comment by aisobran** [comment]
Yeah that was exactly the issue. I think it's good to go..

**Comment by ghost** [comment]
That makes sense @meneal. As long as we are getting values close to 1 we can resubmit.

**Comment by ghost** [comment]
Closed since we have now received credit.
