### ISSUE TITLE
DTLZ

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#29]
There were a number of issues with DTLZ1 that I fixed while trying to debug other issues with the rig overall.  I was thinking that there may be some problem with DTLZ1 when it turned out that in fact the hypervolume setup couldn't deal with more than 2 objectives.  

But while I did that I noticed that there were a number of small bugs in DTLZ1.  Those have been fixed.  I think that at this point we should actually setup DTLZ to run with 3 objectives and whatever the standard number of decisions is for each model and then that should simplify our implementation.  Also when talking to Rahul he suggested to use 3 objectives since they would be easier to graph.  We have truePF's for 3d DTLZ too, so for at least testing purposes 3d should be the better way to go.

One way or the other we need to check all of them and make sure that each is correct.  I think this should be in M1.

**Comment by ghost** [comment]
Are there still bugs in DTLZ? What were some of the bugs you fixed?

**Comment by meneal** [comment]
I've only worked on DTLZ1.  g was subtracted instead of added, and the number of objectives and decisions was equal where it should be done according to the formula n=m+k-1.  From the paper [here](http://www.tik.ee.ethz.ch/sop/publicationListFiles/dtlz2002a.pdf) in the section on performance measures.

You'll see the changes in the "testbranch" branch.  I'm not sure whether there are bugs in the rest of the DTLZ models.

**Comment by ghost** [comment]
Ok. If you'd like I can have a look at these since I started them. I can also try adding the rest of them. 

Just looking at DTLZ5, I'm a bit confused since it refers to a theta function in 2 which I don't see. Also, the theta function calls g(r), but I'm not sure where r comes from. If any of you have answers, let me know. Otherwise, I can look into it tonight and tomorrow before class.

**Comment by ghost** [comment]
I see you've hardcoded the objectives to be 3 for DTLZ1. Is this what you mean to "simplify our implementation"? I agree that it would make the implementation easier, but we would lose flexibility if we wanted anything other than three objectives.

**Comment by meneal** [comment]
Yep. Just hardcode them, when I talked to Rahul he said we should just use
the 3 dimensional objectives anyway.  Also we only have True Frontiers from
JMetal for the 3D versions so we can only calculate spread up to that point
anyway.  We definitely could make them much more flexible, but we really
just don't need that for now.  The most important thing is that the
implementation is correct.

**Comment by ghost** [comment]
Cool, I'll hardcode for 3 objectives. Just want to check another thing. I ran DTLZ1 with 3 objectives and 5 decisions and got SBs with length 7, which is `n_dtlz1`. I want to make sure this is intentional, or should we instead be getting SBs with length 5 to match the number of decisions?

**Comment by meneal** [comment]
Number of decisions is 7.  The equation for number of decisions is n = m +
k - 1 where k is some recommended factor.  In this case k was recommended
as 5.

**Comment by ghost** [comment]
Ah, I see. Sorry about that, I was confused with the all the variables and functions.

**Comment by ghost** [comment]
Just pushed updates to DTLZ2-4 and added 5-7 in testbranch. 

I wasn't sure what `r` referred to in the theta function for DTLZ5 and 6. I found that the authors set `g(r)` to different things, and mentioned that `g(r) = 0` corresponds to the Pareto-optimal front for the theta functions in DTLZ5/6. The paper also says `r` is a "metavariable" which is derived from the decision variables. For now, I simply substituted `r=x` since `g` only works with `x`. I also noticed that the paper says `i` should start at 2 but all the objective functions have theta_1 on them. If anyone has some insights into this it would be greatly appreciated.

**Comment by meneal** [comment]
Check [this](http://opt4j.sourceforge.net/javadoc/3.1.3/src-html/org/opt4j/benchmarks/dtlz/DTLZ5.html#line.56) out.

Also take a look at how [jmetal](https://github.com/jMetal/jMetal/blob/master/jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/dtlz/DTLZ5.java) is doing this.

It looks to me that they are actually just calculating the g function of the vector that's passed in.  I agree that it's confusing though to try to figure out what's going on in the paper.  The weird thing is that there are in fact two papers that cover this same set of test problems and one is sort of more informative than the other in certain situations.  I've listed both in the references issue.

After you look at those two code examples do you think that you have the same interpretation?

**Comment by ghost** [comment]
I agree they're calculating `g` with the vector that's passed in. I also noticed that they're not including the pi/2 terms that appear in the objectives. Rather, they seem to be a part of the theta function.

Before, I was getting negative objective values on the frontier, but that seems to be fixed now. 

I think the paper(s) could be more clear since there's no way I would have made these changes without looking at the links you gave. If anyone notices anomalies with any of the DTLZ models, let me know and I'll have a look.

**Comment by meneal** [comment]
This is done as far as I can tell.
