### ISSUE TITLE
Objective max mins

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#31]
Not tracking the max mins for objectives is screwing up any type of informative output of how the decision pace affects the objective values. We were outputting different size points for the graph based on energy but now that is not possible. These we really useful to see have the particles diverged or converged. 

This will hinder our ability to develop our heuristics as PSO particles travel the decision space. 

Even though we don't use it for the metrics we should put it back in to aid development.

**Comment by meneal** [comment]
I'm totally fine with that just as long as we don't use normalized values with cdom or for output to the metrics.  I just pulled all of it because I was trying to figure out what was going on with the metrics.  

As long as the values for the grapher are stored in the grapher and don't end up in s or sb then it shouldn't be problematic to have them back in there.
