### ISSUE TITLE
IO Bugs

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#34]
Before writing out.txt, we should check if out/ exists or at least make sure the folder exists in the repo.

**Comment by meneal** [comment]
I'm a bit confused about this.  Why wouldn't the folder exist?  Are you thinking that you want to delete the folder for some reason?

**Comment by meneal** [comment]
If the folder doesn't exist python throws an exception because the logger is set up to do that.  Would you rather it do something else?  I could put it into a try catch block, but execution should stop at that point since the logger will have no place to write it's file...  It will stop too before the optimizer is ever run so we shouldn't have issues there.

**Comment by aisobran** [comment]
It doesn't exist because it's in the gitignore. Git won't push an empty folder. I removed it from gitignore so the out folder will exist. 

The other option is to check if the folder exists. This is easier for now. 

It just seems really broken if the first command you run after cloning this repo will always throw an exception as the folder would never exist.

**Comment by meneal** [comment]
That's really weird.  I deleted the repo and cloned it just the other day and the out folder was there.  I wonder when that was added to the .gitignore.  

Yeah it seems broken if it throws that exception when you clone.  I could just setup a line where it would create the directory if the directory doesn't exist.  Does that work?

**Comment by aisobran** [comment]
I think we can just keep it the way it is. But if you want to change it, wait until I push the changes to grapher to include the true pfs.

**Comment by meneal** [comment]
Eh we'll leave it for now then.
