### ISSUE TITLE
cdom or Golinski Bug

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#35]
I get this with Golinski:

```
losses = [math.exp((a - b)/n) for (a,b) in zip(c1, c2)]
OverflowError: math range error
```

**Comment by aisobran** [comment]
Get the same error with Water

**Comment by aisobran** [comment]
Also with DTLZ3. This is either bug with cdom or with these three models.

**Comment by meneal** [comment]
In grapher why is line 24: 
`if len(s.listOfVectors[1][1]) <= 2:`
and not
`if len(s.listOfVectors[1][0]) <= 2:`
?

I'm looking at that DTLZ bug, but I'm getting list index out of range errors in grapher before I hit the overflow.

**Comment by aisobran** [comment]
You're right if there is only one value in the frontier it should be zero.

I'll push a fix with the added true pf support.

**Comment by meneal** [comment]
I'd say right off the bat that it looks like we're stuck with normalizing for at least these models.  I really tried to get away from that mostly because I was having so much trouble getting cdom to work correctly.  

The only other possibility would be to drop these three models.  But I don't think that's a great option.  Once we have normalization rigged back in, I'll figure out how to either use normalization for just these three models or for all of the models.
