### ISSUE TITLE
Reading Part 1: Paper 2

### ISSUE THREAD

**Issue by ghost** [LambdaConglomerate/x9115lam#7]
Our second paper looks to be [A systematic and comprehensive investigation of methods to build and evaluate fault prediction models](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.164.375&rep=rep1&type=pdf). 

It looks like Dr. Menzies was expecting us to have read (or be working on) two papers by now, so I think we should have the paper read by class time on Tuesday and our summary finished by Thursday, if not sooner.

**Comment by meneal** [comment]
I'm fine with that for a timeline.  I think I should be able to read it by Tuesday.

**Comment by aisobran** [comment]
Started the summary and added definitions.

**Comment by ghost** [comment]
I added a couple of feature extraction items, including another go at motivational statements. I also added a possible improvement. Let me know if there's something that doesn't make sense or you disagree with.

**Comment by meneal** [comment]
So I added a bunch of stuff in here.  First I added part of a motivational statement since I'm not totally in agreement on the one that's in there right now.  Perhaps we can combine them?  I added a section on patterns, and informative visualizations, a possible improvements block and I also added in the Connection to other papers section.  

Since we're going to eventually have to turn this info a paper I figured it'd be easier to just start using Bibtex for the references and then we can just reuse them if we have to talk about other papers.  It's a really clean way to to references too since they're in that separate references.bib doc.  Another slick feature is that most of the sites that actually have these research papers will export a citation for the paper to bibtex so no need to really do anything.  Let me know if either of you hasn't used it before and I'll show you how it works.  Any changes to my stuff are definitely welcome.

**Comment by ghost** [comment]
It looks like your motivational statement is a summary of mine. I was going into more detail as to how previous research was lacking. What exactly do you disagree with?

**Comment by meneal** [comment]
So I feel like the first two sentences are a bit confusing.  It states that
"most previous studies" did something and then states "In the few studies
that did", but it's not clear what we're talking about in the second
sentence.

Also I think that what they're saying is not that general conclusions can't
be drawn by using confusion matrices, but that using confusion matrices for
comparison of models alone neglects cost-effectiveness and that cost
effectiveness should be considered in addition to the type of comparison
metrics that can be provided by confusion matrices.

Honestly I think that motivational statements is the hardest feature to
talk about.  We're trying to define the motivation for a 17 page paper in 3
lines.  Definitely not picking on you, I just want to get it right.

**Comment by ghost** [comment]
Sorry, it was supposed to say "In the few studies that did not" instead. I see you're second point, and I've changed "general" to "specific" which means that the conclusions gathered from using confusion matrices won't work in every case. I'm not sure if that's clearer or not.

And I agree that it's hard to talk about motivations, especially since you can be very general. But feel free to change what I've written if you disagree.

**Comment by ghost** [comment]
I'd like to submit this soon. It looks like we have everything we need and our word count is good. What do you guys think about the motivational statements? I think they are both correct and we should combine them.

**Comment by meneal** [comment]
I'd like to get some feedback from Sasha on how he thinks this looks at
this point.  I think it's ok now, but I'm still not totally sure about the
motivational statements I think other than that we're ready to roll.  I
agree that I would prefer to submit this thing today.

**Comment by aisobran** [comment]
I fixed the motivational statement and added a few extra things. I'll submit.
